apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu-container
    image: ubuntu:18.04
    command: ["/bin/bash", "-c"]
    args:
      - >
        apt update &&
        apt install -y  git curl &&
        apt install -y wget build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev &&
        wget https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tgz &&
        tar -xvf Python-3.9.0.tgz &&
        cd Python-3.9.0 &&
        ./configure --enable-optimizations &&
        make -j$(nproc) &&
        make altinstall &&
        update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.9 1 &&
        curl https://bootstrap.pypa.io/get-pip.py | python3 &&
        pip install boto3 requests &&
        git clone https://github.com/jefrnc/debug-deploys.git &&
        sleep 3600
